### ISSUE TITLE
[Feature Req] Non-Square Window Functions

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/pspec_likelihood#39]
Currently, the window functions are enforced to be square -- the size of the data power on each axis. In general, they do not have to be square, but could be higher-resolution along one axis. This would allow higher-resolution theory models to be gridded back to the data space appropriately. Currently, the user has to do the work of returning the theory exactly at the same k as the observations.

**Comment by adeliegorce** [comment]
The shape of the window functions does actually not seem to be a problem since all the arrays are flattened through the block diagonal, e.g., 
- For exact window functions, the WF array of shape `(kper_bins_obs, kpar_bins_obs, kper_bins_theory, kpar_bins_theory)` becomes shape `(kper_bins_obs * kpar_bins_obs, kper_bins_theory * kpar_bins_theory)`.
- For approximate window functions, the WF array of shape `(Nblpairs, Ndelays, Ndelays)` becomes `(Nblpairs * Ndelays, Nblpairs * Ndelays)`.

When testing for cylindrical window functions, I did ensure there was no issue there (hence the link between this issue and #49)
